apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier
  namespace: webhooks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifier
  template:
    metadata:
      labels:
        app: notifier
    spec:
      containers:
      - name: template
        image: registry.bank131.ru/kzn/infra/notifier:v10
        ports:
        - containerPort: 9000
        resources:
          limits:
            cpu: 20m
            memory: 50Mi
          requests:
            cpu: 20m
            memory: 50Mi
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: notifier
  namespace: webhooks
  labels:
    service: notifier
spec:
  selector:
    app: notifier
  type: ClusterIP
  ports:
  - port: 9000

---



